name: snap

on:
  workflow_call:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  snap:
    uses: canonical/robotics-actions-workflows/.github/workflows/snap.yaml@fix/refactor-matrix
    with:
      snap-test-script: |
        #!/bin/sh
        set -euxo pipefail
        hello-snap | grep "Hello World"
    # secrets:
    #   snapstore-login: ${{ secrets.SNAPSTORE_LOGIN }}
