name: snap-multi-arch

on:
  workflow_call:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main


jobs:
  build:
    uses: canonical/robotics-actions-workflows/.github/workflows/build.yaml@fix/refactor_guillaume
    with:
      runs-on: '["self-hosted", "linux", "ARM64", "medium", "noble"]'

  test:
    needs: [build]
    uses: canonical/robotics-actions-workflows/.github/workflows/test.yaml@fix/refactor_guillaume
    with:
      lxc-image: 'ubuntu:20.04'
      runs-on: '["self-hosted", "linux", "ARM64", "medium", "noble"]'
      snap-artifact: ${{ needs.build.outputs.snap-artifact-name }}
      snap-test-script: |
        #!/bin/sh
        set -euxo pipefail
        hello-world | grep "hello-world"

  publish:
    needs: [build, test]
    uses: canonical/robotics-actions-workflows/.github/workflows/publish.yaml@fix/refactor_guillaume
    with:
      snap-artifact: ${{ needs.build.outputs.snap-artifact-name }}
      snap-track: latest
    secrets:
      snapstore-login: ${{ secrets.snapstore-login }}
