name: snap-multi-arch

on:
  workflow_call:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main


jobs:
  build:
    strategy:
      matrix:
        runner: ['ubuntu-latest', '["self-hosted", "linux", "ARM64", "medium", "noble"]']
    uses: ./.github/workflows/_snap.yaml
    with:
      runs-on: ${{ matrix.runner }}
